class Product {
  final int id;
  final String name;
  final String type;
  final String description;
  final String price;
  final int likes;
  final String imagePath;

  Product({
    required this.id,
    required this.name,
    required this.type,
    required this.imagePath,
    required this.description,
    required this.price,
    required this.likes,
  });
}

final dataProduct = [
    Product(
      id: 1,
      name: 'Americano Coffe',
      type: 'KOPI',
      description: "Americano coffee adalah minuman kopi yang terbuat dari espresso yang ditambahkan air panas. Asal-usul namanya berasal dari cerita para tentara Amerika Serikat yang pernah berada di Eropa pada Perang Dunia II, di mana mereka sering memesan espresso dan menambahkan air panas untuk membuatnya lebih ringan dan mirip dengan kopi yang biasa diminum di Amerika Serikat.",
      price: "Rp 18.000",
      imagePath: 'assets/images/product/Americano-Coffee.jpeg',
      likes: 102,
    ),
    Product(
      id: 2,
      name: 'Avocado Coffe',
      type: 'KOPI',
      description: "Avocado coffee adalah jenis minuman kopi yang menggunakan alpukat yang dihaluskan atau diblender sebagai salah satu bahan utamanya. Kreasi kopi yang unik ini semakin populer dalam beberapa tahun terakhir, terutama di Asia Tenggara dan Australia. Untuk membuat avocado coffee, biasanya alpukat yang sudah matang dihaluskan atau diblender dengan kopi, kemudian ditambahkan susu atau creamer serta pemanis jika diinginkan. Minuman ini memiliki cita rasa yang unik dan creamy karena kandungan lemak sehat dari alpukat yang tercampur dengan rasa kopi. Avocado coffee sering dijadikan alternatif bagi mereka yang ingin mencoba sesuatu yang berbeda dari kopi pada umumnya.",
      price: "Rp 30.000",
      imagePath: 'assets/images/product/avocado-coffee.jpeg',
      likes: 75,
    ),
    Product(
      id: 3,
      name: 'Capuccino Latte',
      type: 'KOPI',
      description: 'Cappuccino Latte adalah minuman kopi yang terdiri dari dua lapisan, yaitu espresso dan susu dengan foam di atasnya. Minuman ini sering dipesan di kedai kopi dan menjadi salah satu varian kopi yang paling populer. Proses pembuatan Cappuccino Latte dimulai dengan pembuatan satu atau dua shot espresso, kemudian ditambahkan susu dengan foam yang lembut di atasnya. ',
      price: "Rp 25.000",
      imagePath: 'assets/images/product/Cappuccino.jpeg',
      likes: 92,
    ),
    Product(
      id: 4,
      name: 'Cheese John',
      type: 'ROTI',
      description: 'Roti Cheese John adalah roti lapis yang terdiri dari roti putih yang diisi dengan irisan daging sapi, keju, saus tomat, dan saus mayones. Roti ini biasanya dipanggang hingga keju meleleh dan disajikan dalam potongan-potongan kecil atau dipotong menjadi dua bagian. Roti Cheese John menjadi populer di Indonesia dan sering ditemukan di kedai-kedai kopi atau penjual makanan jalanan. Roti ini memiliki rasa yang gurih, creamy, dan sedikit manis sehingga sangat cocok dijadikan sebagai camilan atau sarapan.',
      price: "Rp 45.000",
      imagePath: 'assets/images/product/cheese-jhon.jpeg',
      likes: 129,
    ),
    Product(
      id: 5,
      name: 'Coffe Bun',
      type: 'ROTI',
      description: 'Roti Coffee Bun adalah roti manis yang berasal dari Jepang dan populer di berbagai negara di Asia. Roti ini terbuat dari adonan roti yang lembut dan diisi dengan selai kopi di dalamnya. Roti ini juga sering diberi topping biji kopi atau kacang almond di atasnya sebelum dipanggang. Ketika dipanggang, roti ini mengeluarkan aroma kopi yang harum dan menarik. Rasanya yang manis dan kopi yang kuat membuat Roti Coffee Bun menjadi camilan yang populer dan cocok disajikan dengan secangkir kopi atau teh. Roti ini sering ditemukan di toko roti dan kedai kopi, dan merupakan pilihan yang populer di antara penggemar kopi dan roti manis.',
      price: "Rp 15.000",
      imagePath: 'assets/images/product/Resep-Mexican-Coffee-Bun.jpeg',
      likes: 120,
    ),
    Product(
      id: 6,
      name: 'Roti Bakar',
      type: 'ROTI',
      description: 'Roti Bakar adalah roti yang dipanggang atau dibakar di atas api atau pemanggang, biasanya setelah diolesi mentega atau margarin, dan kemudian disajikan dengan berbagai topping. Roti Bakar dapat disajikan dalam berbagai variasi, seperti roti bakar keju, roti bakar coklat, roti bakar telur, dan sebagainya. Roti ini sering dijadikan sarapan atau camilan ringan karena mudah dan cepat untuk disiapkan. Roti Bakar juga dapat disajikan dalam berbagai bentuk, seperti potongan persegi atau segitiga, atau dalam bentuk yang lebih kreatif seperti roti panggang gulung atau roti panggang pangsit. Roti Bakar sering ditemukan di warung-warung kopi, restoran, atau dijual sebagai makanan jalanan.',
      price: "Rp 12.000",
      imagePath: 'assets/images/product/roti-bakar-1.jpeg',
      likes: 111,
    ),
    Product(
      id: 7,
      name: 'Roti Abon Gulung',
      type: 'ROTI',
      description: 'Roti Abon Gulung adalah roti lapis yang diisi dengan abon sapi atau ayam yang dibungkus dan digulung dalam lembaran roti tipis. Roti ini biasanya dipanggang hingga kecoklatan dan dilapisi dengan telur agar tampak mengkilap. Roti Abon Gulung sering dijadikan camilan atau sarapan praktis karena mudah disajikan dan rasanya yang gurih dan lezat. Roti ini dapat ditemukan di toko roti, pasar tradisional, atau pedagang makanan jalanan. Roti Abon Gulung juga sering dijadikan sebagai oleh-oleh atau hadiah karena mudah dibawa dan disimpan dalam kemasan yang praktis.',
      price: "Rp 20.000",
      imagePath: 'assets/images/product/resep-roti-gulung-abon.jpeg',
      likes: 105,
    ),
    Product(
      id: 8,
      name: 'Sandwich',
      type: 'ROTI',
      description: 'Roti Coffee Bun adalah roti manis yang berasal dari Jepang dan populer di berbagai negara di Asia. Roti ini terbuat dari adonan roti yang lembut dan diisi dengan selai kopi di dalamnya. Roti ini juga sering diberi topping biji kopi atau kacang almond di atasnya sebelum dipanggang. Ketika dipanggang, roti ini mengeluarkan aroma kopi yang harum dan menarik. Rasanya yang manis dan kopi yang kuat membuat Roti Coffee Bun menjadi camilan yang populer dan cocok disajikan dengan secangkir kopi atau teh. Roti ini sering ditemukan di toko roti dan kedai kopi, dan merupakan pilihan yang populer di antara penggemar kopi dan roti manis.',
      price: "Rp 10.000",
      imagePath: 'assets/images/product/097371900_1591628474-club-sandwich-served-on-chopping-board-1600711.jpeg',
      likes: 129,
    ),
    Product(
      id: 9,
      name: 'Es Matcha',
      type: 'MINUMAN',
      description: 'Matcha adalah teh hijau alami yang rasa manis',
      price: "Rp 18.000",
      imagePath: 'assets/images/product/54dbbf0c8f1b9a8ceca91894b8e8f7f9.jpeg',
      likes: 155,
    ),
    Product(
      id: 10,
      name: 'Es Teh Manis',
      type: 'MINUMAN',
      description: 'Teh manis dengan ditambah es batu alami',
      price: "Rp 8.000",
      imagePath: 'assets/images/product/es-teh-manis-1.jpeg',
      likes: 135,
    ),
     Product(
      id: 11,
      name: 'Es Anget',
      type: 'MINUMAN',
      description: 'Teh anget ditambah gula sehingga rasanya manis',
      price: "Rp 8.000",
      imagePath: 'assets/images/product/es-teh-manis-1.jpeg',
      likes: 170,
    ),
    Product(
      id: 12,
      name: 'Es Lemon Tea',
      type: 'MINUMAN',
      description: 'Teh manis dicampur lemon dan ditambah es batu alami',
      price: "Rp 10.000",
      imagePath: 'assets/images/product/lemon-tea-selasih.jpeg',
      likes: 90,
    ),
    Product(
      id: 13,
      name: 'Cheese Burger',
      type: 'BURGER',
      description: 'Burger dengan slash keju dan patty daging',
      price: "Rp 25.000",
      imagePath: 'assets/images/product/5f5e37fbbe693.png',
      likes: 110,
    ),
    Product(
      id: 14,
      name: 'Beef Burger',
      type: 'BURGER',
      description: 'Beef burger adalah sejenis makanan cepat saji yang terdiri dari roti berbentuk bundar yang diiris secara horizontal, diisi dengan patty atau daging cincang yang telah dibentuk, sayuran seperti selada, tomat, dan bawang, serta saus atau bumbu seperti mayones, mustard, ketchup, atau saus tomat. Patty daging yang digunakan dalam beef burger umumnya terbuat dari daging sapi segar yang telah dicincang kasar dan dicampur dengan bumbu seperti garam, merica, bawang putih, atau paprika, lalu dibentuk menjadi bola dan ditekan hingga rata. Patty kemudian dipanggang, dibakar, atau digoreng hingga matang sesuai dengan selera. Beef burger biasanya disajikan dengan kentang goreng atau onion ring sebagai pelengkapnya. Makanan ini populer di seluruh dunia dan banyak ditemukan di restoran cepat saji atau warung makan yang menyajikan makanan siap saji.',
      price: "Rp 35.000",
      imagePath: 'assets/images/product/622358ed771fb.jpeg',
      likes: 90,
    ),
    Product(
      id: 15,
      name: 'Chicken Burger',
      type: 'BURGER',
      description: 'Beef burger adalah sejenis makanan cepat saji yang terdiri dari roti berbentuk bundar yang diiris secara horizontal, diisi dengan patty atau daging cincang yang telah dibentuk, sayuran seperti selada, tomat, dan bawang, serta saus atau bumbu seperti mayones, mustard, ketchup, atau saus tomat. Patty daging yang digunakan dalam beef burger umumnya terbuat dari daging sapi segar yang telah dicincang kasar dan dicampur dengan bumbu seperti garam, merica, bawang putih, atau paprika, lalu dibentuk menjadi bola dan ditekan hingga rata. Patty kemudian dipanggang, dibakar, atau digoreng hingga matang sesuai dengan selera. Beef burger biasanya disajikan dengan kentang goreng atau onion ring sebagai pelengkapnya. Makanan ini populer di seluruh dunia dan banyak ditemukan di restoran cepat saji atau warung makan yang menyajikan makanan siap saji.',
      price: "Rp 30.000",
      imagePath: 'assets/images/product/chicken-mcmuffin-with-egg-0-1541616849.png',
      likes: 92,
    ),
    Product(
      id: 16,
      name: 'Beef Chicken Burger',
      type: 'BURGER',
      description: 'Chicken beef burger adalah varian dari burger yang terbuat dari daging ayam yang dicincang halus atau diiris tipis, kemudian dibentuk menjadi patty atau irisan dada ayam yang diolah dengan berbagai bumbu dan rempah-rempah untuk menambah rasa. Patty ayam tersebut kemudian dipanggang, dibakar, atau digoreng hingga matang..',
      price: "Rp 32.000",
      imagePath: 'assets/images/product/resep-mini-cheese-burger_43.jpeg',
      likes: 90,
    ),
    Product(
      id: 17,
      name: 'Eskrim Coklat',
      type: 'ESKRIM',
      description: 'Es krim coklat adalah varian es krim yang menggunakan coklat sebagai bahan utamanya, sehingga memberikan rasa manis dan lezat dengan aroma yang khas. Es krim coklat umumnya terbuat dari campuran susu segar, gula, coklat bubuk, dan bahan-bahan lainnya seperti krim kental atau vanilla.',
      price: "Rp 15.000",
      imagePath: 'assets/images/product/5ee24345ec640.jpeg',
      likes: 78,
    ),
    Product(
      id: 18,
      name: 'Eskrim Strawberry',
      type: 'ESKRIM',
      description: 'Es krim Strawberry adalah varian es krim yang menggunakan Strawberry sebagai bahan utamanya, sehingga memberikan rasa manis dan lezat dengan aroma yang khas. Es krim Strawberry umumnya terbuat dari campuran susu segar, gula, Strawberry bubuk, dan bahan-bahan lainnya seperti krim kental atau vanilla.',
      price: "Rp 15.000",
      imagePath: 'assets/images/product/strawberry-cone__36657.jpeg',
      likes: 120,
    ),
    Product(
      id: 19,
      name: 'Eskrim Vanilla',
      type: 'ESKRIM',
      description: 'Es krim vanilla adalah varian es krim yang menggunakan vanilla sebagai bahan utamanya, sehingga memberikan rasa manis dan lezat dengan aroma yang khas. Es krim vanilla umumnya terbuat dari campuran susu segar, gula, vanilla bubuk, dan bahan-bahan lainnya seperti krim kental atau vanilla.',
      price: "Rp 15.000",
      imagePath: 'assets/images/product/DC_202106_0336_LargeVanillaCone_832x472_1-3-product-tile-desktop.jpeg',
      likes: 131,
    ),
    Product(
      id: 20,
      name: 'Pizza Tuna Melt',
      type: 'PIZZA',
      description: 'Pizza tuna Melt adalah sebuah sandwich atau roti lapis yang terdiri dari dua lembar roti yang diisi dengan keju mozzarella, saus tomat, dan topping seperti pepperoni, daging sapi cincang, paprika, dan jamur. Kemudian roti tersebut dipanggang atau dipanggang di atas wajan dengan sedikit mentega hingga keju mozzarella meleleh dan roti menjadi garing. Pizza Melt merupakan varian dari pizza yang lebih praktis dan mudah disajikan. Makanan ini umumnya disajikan panas dan sering ditemukan di restoran cepat saji atau kedai makanan.',
      price: "Rp 130.000",
      imagePath: 'assets/images/product/d79572ae-77a3-44b4-8e15-a28447c5c040.jpeg',
      likes: 221,
    ),
    Product(
      id: 21,
      name: 'Pizza Meaty',
      type: 'PIZZA',
      description: 'Pizza Meaty adalah varian pizza yang terdiri dari adonan pizza yang ditaburi dengan saus tomat, keju mozzarella, dan berbagai macam daging seperti pepperoni, daging sapi cincang, daging babi asap, dan sosis. Topping daging pada pizza meaty memberikan rasa gurih dan sedikit asin yang sangat disukai oleh pecinta daging. Pizza Meaty biasanya disajikan dalam bentuk bulat dan potongan segitiga, dan menjadi salah satu varian pizza yang paling populer di seluruh dunia.',
      price: "Rp 140.000",
      imagePath: 'assets/images/product/IMG_20190402_141757_6.jpeg',
      likes: 191,
    ),
    Product(
      id: 22,
      name: 'Pizaa Limo 1 Meter',
      type: 'PIZZA',
      description: 'Pizza limo 1 meter adalah varian pizza yang sangat besar, memiliki ukuran panjang sekitar 1 meter dengan lebar yang bervariasi. Pizza ini terdiri dari adonan pizza yang ditaburi dengan saus tomat, keju mozzarella, dan berbagai macam topping seperti daging sapi cincang, sosis, pepperoni, jamur, paprika, bawang, dan lain sebagainya. Pizza limo 1 meter biasanya disajikan untuk kelompok besar atau acara-acara khusus karena ukurannya yang sangat besar dan dapat memenuhi kebutuhan banyak orang. Makanan ini biasanya ditemukan di restoran-restoran pizza yang menyediakan pilihan pizza dalam ukuran besar atau extra large.',
      price: "Rp 235.000",
      imagePath: 'assets/images/product/Pizza-Hut-1-Meter-Toppingnya-Apa-Untuk-Berapa-Orang-Potongannya.jpeg',
      likes: 310,
    ),
    Product(
      id: 23,
      name: 'Nasi Kebuli Ayam',
      type: 'NASI',
      description: 'Nasi Kebuli Ayam adalah sebuah hidangan nasi yang terbuat dari nasi basmati yang dimasak dengan campuran rempah dan bumbu khas Timur Tengah seperti kayu manis, cengkeh, dan kapulaga. Nasi kebuli ayam biasanya disajikan dengan daging ayam yang telah dimasak dengan rempah-rempah seperti kunyit, jahe, dan bawang putih. Daging ayam tersebut biasanya dipotong kecil-kecil dan disajikan bersama dengan nasi kebuli yang harum dan gurih.',
      price: "Rp 45.000",
      imagePath: 'assets/images/product/shutterstock_2102653033.jpeg',
      likes: 172,
    ),
    Product(
      id: 24,
      name: 'Nasi Goreng Spesial',
      type: 'NASI',
      description: 'Nasi goreng rendang spesial adalah varian nasi goreng yang menggunakan rendang sebagai bahan utamanya. Rendang adalah sebuah hidangan daging asli dari Minangkabau yang terbuat dari daging sapi yang dimasak dalam santan dan bumbu rempah khas Indonesia yang kaya akan rasa dan aroma.',
      price: "Rp 22.000",
      imagePath: 'assets/images/product/resep-nasi-goreng-rendah-kalori-cocok-untuk-diet-D8kxJ8GTcT.jpeg',
      likes: 541,
    ),
    Product(
      id: 25,
      name: 'Nasi Gudeg',
      type: 'NASI',
      description: 'Nasi Gudeg adalah hidangan nasi khas Jawa yang terbuat dari nangka muda yang dimasak dengan santan dan rempah-rempah seperti daun salam, lengkuas, dan bawang merah. Nangka muda tersebut dimasak hingga empuk dan berubah warna menjadi cokelat kehitaman. Selain nangka muda, nasi gudeg juga disajikan dengan telur rebus, ayam suwir, dan sambal goreng krecek yang terbuat dari kulit sapi.',
      price: "Rp 25.000",
      imagePath: 'assets/images/product/gudeg.jpeg',
      likes: 127,
    ),
    Product(
      id: 26,
      name: 'Nasi Liwet',
      type: 'NASI',
      description: 'Nasi liwet adalah hidangan nasi khas Indonesia yang berasal dari daerah Jawa Barat, terutama dari daerah Sunda. Hidangan ini terdiri dari nasi yang dimasak bersama dengan santan, bawang merah, dan daun pandan sehingga memiliki aroma yang harum dan gurih.Nasi liwet biasanya disajikan dengan lauk-pauk seperti ayam goreng, ikan asin, atau tempe goreng, serta sambal terasi dan sayur-sayuran seperti terong dan lalapan. Hidangan ini biasanya disajikan dalam porsi kecil dan dimakan dengan cara dicampur dengan lauk pauk dan sayuran sehingga menciptakan perpaduan rasa yang lezat.',
      price: "Rp 15.000",
      imagePath: 'assets/images/product/37082d73-70c9-446c-8d3d-e74d08527084.jpeg',
      likes: 88,
    ),
    Product(
      id: 27,
      name: 'Cumi Asem Manis',
      type: 'SEAFOOD',
      description: 'Cumi asam manis adalah hidangan masakan laut yang populer di Indonesia, khususnya di daerah pantai. Hidangan ini terdiri dari cumi-cumi yang digoreng hingga renyah dan kemudian disiram dengan saus asam manis yang terbuat dari campuran saus tomat, saus cabai, gula, cuka, dan air.',
      price: "Rp 40.000",
      imagePath: 'assets/images/product/cumi-asem-manis.png',
      likes: 88,
    ),
    Product(
      id: 28,
      name: 'Cumi Goreng Crispy',
      type: 'SEAFOOD',
      description: 'Cumi goreng crispy adalah hidangan laut yang sangat populer di seluruh dunia. Hidangan ini terdiri dari cumi-cumi yang dilapisi tepung kering dan kemudian digoreng hingga renyah dan garing.',
      price: "Rp 25.000",
      imagePath: 'assets/images/product/cumi-kriuk.jpeg',
      likes: 88,
    ),
    Product(
      id: 29,
      name: 'Cumi Goreng Hokben',
      type: 'SEAFOOD',
      description: 'Cumi crispy Hokben adalah hidangan laut yang biasa disajikan di restoran cepat saji Hokben di Indonesia. Hidangan ini terdiri dari cumi-cumi segar yang dipotong-potong dan digoreng dengan tepung kering hingga renyah dan garing.',
      price: "Rp 55.000",
      imagePath: 'assets/images/product/resep-ebi-furai-hokben_43.jpeg',
      likes: 182,
    ),
    Product(
      id: 29,
      name: 'Udang Bakar',
      type: 'SEAFOOD',
      description: 'Udang bakar adalah hidangan laut yang sangat populer di Indonesia dan banyak negara lain di dunia. Hidangan ini terdiri dari udang yang dibersihkan, kemudian dibumbui dengan bumbu rempah seperti bawang putih, ketumbar, jahe, dan cabai, dan kemudian dipanggang atau dibakar hingga matang.',
      price: "Rp 30.000",
      imagePath: 'assets/images/product/udang-bakar.jpeg',
      likes: 198,
    ),
    

  ];